#!/usr/bin/env python3

"""Generate the RV64I portion of the local RV64IM encoding API."""

from __future__ import annotations

import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
RISCV_OPCODES_SRC = REPO_ROOT / "reference" / "riscv-opcodes" / "src"

sys.path.insert(0, str(RISCV_OPCODES_SRC))

from riscv_opcodes.constants import arg_lut  # noqa: E402
from riscv_opcodes.shared_utils import create_inst_dict  # noqa: E402


HEADER_GUARD = "BAREMETAL_HIGH_LEVEL_PROTOTYPE_RV64IM_API_H"
MERGED_FIELD_PAIRS = {
    ("imm12hi", "imm12lo"): "imm",
    ("bimm12hi", "bimm12lo"): "imm",
}
DIRECT_PARAM_NAMES = {
    "imm12": "imm",
    "imm20": "imm",
    "jimm20": "imm",
    "shamtd": "shamt",
    "shamtw": "shamt",
}
LOGICAL_FIELD_ORDERS = {
    ("imm12hi", "rs1", "rs2", "imm12lo"): ("rs1", "rs2", "imm"),
    ("bimm12hi", "rs1", "rs2", "bimm12lo"): ("rs1", "rs2", "imm"),
}


def c_mask(width: int) -> str:
    return hex((1 << width) - 1)


def instruction_params(fields: list[str]) -> list[tuple[str, str]]:
    params: list[tuple[str, str]] = []
    emitted: set[str] = set()

    for field in fields:
        if field in emitted:
            continue

        merged = next(
            (
                (pair, param_name)
                for pair, param_name in MERGED_FIELD_PAIRS.items()
                if field == pair[0] and pair[1] in fields
            ),
            None,
        )
        if merged is not None:
            pair, param_name = merged
            params.append((param_name, "int"))
            emitted.update(pair)
            continue

        params.append((DIRECT_PARAM_NAMES.get(field, field), "int"))
        emitted.add(field)

    logical_order = LOGICAL_FIELD_ORDERS.get(tuple(fields))
    if logical_order is None:
        return params

    param_by_name = {name: (name, c_type) for name, c_type in params}
    return [param_by_name[name] for name in logical_order]


def field_expression(field: str) -> str:
    if field == "rd":
        return "(((uint32_t)rd) & 0x1fu) << 7"
    if field == "rs1":
        return "(((uint32_t)rs1) & 0x1fu) << 15"
    if field == "rs2":
        return "(((uint32_t)rs2) & 0x1fu) << 20"
    if field == "imm12":
        return "(((uint32_t)imm) & 0xfffu) << 20"
    if field == "imm12hi":
        return "((((uint32_t)imm) >> 5) & 0x7fu) << 25"
    if field == "imm12lo":
        return "(((uint32_t)imm) & 0x1fu) << 7"
    if field == "bimm12hi":
        return (
            "((((uint32_t)imm) >> 12) & 0x1u) << 31 | "
            "((((uint32_t)imm) >> 5) & 0x3fu) << 25"
        )
    if field == "bimm12lo":
        return (
            "((((uint32_t)imm) >> 1) & 0xfu) << 8 | "
            "((((uint32_t)imm) >> 11) & 0x1u) << 7"
        )
    if field == "imm20":
        return "(((uint32_t)imm) & 0xfffffu) << 12"
    if field == "jimm20":
        return (
            "((((uint32_t)imm) >> 20) & 0x1u) << 31 | "
            "((((uint32_t)imm) >> 1) & 0x3ffu) << 21 | "
            "((((uint32_t)imm) >> 11) & 0x1u) << 20 | "
            "((((uint32_t)imm) >> 12) & 0xffu) << 12"
        )
    if field == "shamtd":
        return "(((uint32_t)shamt) & 0x3fu) << 20"
    if field == "shamtw":
        return "(((uint32_t)shamt) & 0x1fu) << 20"

    msb, lsb = arg_lut[field]
    width = msb - lsb + 1
    return f"(((uint32_t){field}) & {c_mask(width)}u) << {lsb}"


def emit_instruction(name: str, info: dict[str, object]) -> str:
    fields = info["variable_fields"]  # type: ignore[index]
    match = info["match"]  # type: ignore[index]
    params = instruction_params(fields)
    signature = ", ".join(f"{c_type} {param}" for param, c_type in params) or "void"

    body = [f"  uint32_t instruction = {match}u;"]
    for field in fields:
        body.append(f"  instruction |= {field_expression(field)};")
    body.append("  return instruction;")

    return "\n".join(
        [
            f"__attribute__((unused)) static inline uint32_t rv64i_{name}({signature}) {{",
            *body,
            "}",
        ]
    )


def generate_header() -> str:
    instr_dict = create_inst_dict(["rv_i", "rv64_i"], include_pseudo=False)
    functions = [
        emit_instruction(name, instr_dict[name]) for name in sorted(instr_dict.keys())
    ]

    return "\n".join(
        [
            "/* Auto-generated by baremetal/high_level_prototype/gen_rv64im_api.py. */",
            f"#ifndef {HEADER_GUARD}",
            f"#define {HEADER_GUARD}",
            "",
            "#include <stdint.h>",
            "",
            *functions,
            "",
            f"#endif /* {HEADER_GUARD} */",
            "",
        ]
    )


def main() -> int:
    sys.stdout.write(generate_header())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
